### ISSUE TITLE
Frontend Admin

### ISSUE THREAD

**Issue by Entenfan** [Entenfan/web_app_bray#1]
Nachdem man durch SQL Injection das Admin Passwort erhalten hat, kann man sich als Admin anmelden. Dieser soll man auf eine rudimentäre Admin-Seite, von der man dann Zugriff auf den Server erhalten kann (hier stellt sich noch die Frage auf welchem Weg).
Dafür braucht man ein kleines Frontend (nichts besonderes oder schönes), auf dem man bspw. ein Eingabefeld hat.

**Comment by Entenfan** [comment]
@ricky3001 sieht soweit gut aus, ich habe die Navbar angepasst, dass man wieder auf die anderen Seiten zurückkommt

**Comment by ricky3001** [comment]
@Entenfan ja das hab ich nicht hinbekommen, deshalb die andere

**Comment by ricky3001** [comment]
searchBar
https://uiverse.io/denswastaken/stupid-jellyfish-26

checklist
https://uiverse.io/JkHuger/warm-panther-74

**Comment by ricky3001** [comment]
Vorgehen @TaeOh23 
1. Grundidee was wird benötigt 
    - SearchBar -> für Injection
    - NavBar -> um zu anderen Seiten zu gelangen
    - Extras -> toDo List
2. Mit HTML und CSS vertraut machen
    - verschiedene Komponenten und Layouts ausprobieren
    - Was sieht wie aus wenn ich was verändere
3. CSS Style Sheet anlegen und ausgewählte Komponenten Anpassen
4. HTML Datei anlegen und mit Style sheet verknüpfen
5. kleine Nachbesserungen
