### ISSUE TITLE
Schriftliche Ausarbeitung

### ISSUE THREAD

**Issue by Entenfan** [Entenfan/web_app_bray#7]
- [ ]  Schriftliche Ausarbeitung
- [ ] Musterlösung
- [ ] Präsentation: https://studhsheilbronnde-my.sharepoint.com/:p:/g/personal/ngeck_stud_hs-heilbronn_de/EbVQ5556CmpJmKcbAbRtktYBmSrhRaueo4WzttNd01ISOg?e=7haEBA

**Comment by TaeOh23** [comment]
Also ich habe jetzt endlich mal die Theorie fertig. Ich lese sie jetzt nochmal Korrektur, werde aber schon mal den jetzigen Stand hochladen :)
[Schriftliche_Ausarbeitung_PSSWE-1.pdf](https://github.com/Entenfan/SSWEHackShop/files/11525694/Schriftliche_Ausarbeitung_PSSWE-1.pdf)

**Comment by Entenfan** [comment]
Also ich weiß nicht, ob du schon mit der Story angefangen hast, aber so als Idee könnte man ja ein paar "untypische" Dinge für einen Klamottenladen auf der Webseite verstecken. Ein Bild von nem T-Shirt mit was anderem austauschen, oder mal einen Text von einem Produkt ändern, vllt könnte man ja in ein paar fehlerhaften ausgaben (z.B. beim fehlerhaften Login wo man die SQL-Query mit dem Comment bekommt) so ein bisschen "Charakter" von den Betreiber der Webseite durschscheinen lassen

**Comment by TaeOh23** [comment]
Also ich hab wieder was in der schriftlichen Ausarbeitung geändert. Ist jetzt nicht viel was. Aber ich lade mal hier den Source code hoch , damit ihr (@Entenfan und @ricky3001) auch Zugriff habt, da Overleaf ja nur mit einer Person teilt. 

[Schriftliche Ausarbeitung PSSWE.zip](https://github.com/Entenfan/SSWEHackShop/files/11764250/Schriftliche.Ausarbeitung.PSSWE.zip)

Die nächsten Tage versuche ich es zumindest bisschen zu kürzen + die Sachen zu erweitern. Wer helfen mag, kann gerne Bescheid geben^^.
